### PR TITLE
Remove 18F logo from footer and update text refer to OPP

### LINKED ISSUE #432: Remove 18F logo in footer?
Since the project is no longer under run by 18F, should we remove the logo in the footer? Or replace it with something else (OPP, TTS)?

screen shot 2017-11-01 at 4 13 14 pm

We still link to and advertise training offerings on the homepage, which I assume will be processed by 18F so maybe that's a reason to keep it in? 

/cc @thisisdano

### PR DESCRIPTION
**Pull request by maya**
Fixes #432.

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-footer)

### CODE REVIEW

**Comment by thisisdano** [comment]
Let's link from `Federalist` to `https://federalist.18f.gov/`. (The other references — GSA, TTS, etc — don't need a link as far as I'm concerned.)

**Comment by maya** [comment]
@thisisdano removed the TTS link in dda12f6, leaving Federalist linked.

**Comment by maya** [comment]
Also, pretty sure https://federalist.fr.cloud.gov is the correct link, not the 18F one.

**Comment by maya** [comment]
@thisisdano this is ready for review.

**Comment by thisisdano** [comment]
Only issue I see is that the Federalist link is functionally invisible — it doesn't have any indication that it's a link. I suggest a Classic Underline.

**Comment by maya** [comment]
@thisisdano that code is not coming from the styleguide.scss. Seems as though USWDS is removing it. Maybe open an issue on USWDS repo?

**Comment by thisisdano** [comment]
Yeesh. GD USWDS.
OK, then. Merge as is, and we'll address in a subsequent `wds` issue/PR.

**Comment by maya** [comment]
Ah ok! Using my special/scary admin privileges to override the review, feel free to `approve` in the future so I get a green light.

**Comment by thisisdano** [comment]
Ha, oops. Shoulda just approved.
New underlining issue here: https://github.com/18F/web-design-standards/issues/2219

**Pull request merged**
