### PR TITLE
Update staging branch to match staging on `web-design-standards` repo

### PR DESCRIPTION
**Pull request by juliaelman**
This pull requests incorporates all of the new updates merged into staging on the [web-design-standards](https://github.com/18F/web-design-standards/) repo.

### CODE REVIEW

**Comment by juliaelman** [comment]
Fixes #1

**Comment by maya** [comment]
Looks like the search button is dropping to the next line:

screen shot 2016-09-13 at 1 14 54 pm

**Comment by maya** [comment]
Also, noticing that the navigation header scroll starts too late now:

**Comment by maya** [comment]
Also, seeing the search issue happen on search component page so it looks like an issue related to something else in the codebase:

screen shot 2016-09-13 at 1 24 23 pm

**Comment by maya** [comment]
Normalize's 
```
input[type="search"] {
  box-sizing: content-box;
}
```
is causing the issue bc it is overriding `input {box-sizing: border-box}`

**Comment by maya** [comment]
When #35 is merged in, this is good to go.

The search bug is a separate issue and can be fixed in the https://github.com/18F/web-design-standards repo.

**Comment by juliaelman** [comment]
Right on ^5 Merged in the `sticky nav` fix and opened the following issue for solving the search bar issue in the Standards: https://github.com/18F/web-design-standards/issues/1481

Thanks all!

**Pull request merged**
