### PR TITLE
Add AccessLint CI to run accessibility tests

### PR DESCRIPTION
**Pull request by ckundo**
## Description
- Runs [accesslint-ci](https://robots.thoughtbot.com/introducing-accesslint-web-accessibility-testing-in-ci) on the entire site for new pull requests and comments on the PR with accessibility issues.
- CI will _not_ fail on accessibility errors. accesslint-ci will comment on the pull requests.
- The first PR with this change will list all of the accessibility issues on the site.
- Subsequent PRs will only receive comments there are new changes.
## Additional Information
- Installs [`accesslint-cli`](https://github.com/accesslint/accesslint-cli.js).
  - `accesslint-cli` is a node module that injects the [axe-core](https://github.com/dequelabs/axe-core) library into a page to run accessibility tests.
- Installs [`accesslint-ci`](https://github.com/accesslint/accesslint-ci).
  - crawls a host and passes the urls to `accesslint-cli` for accessibility evaluation.
- Set `ACCESSLINT_MASTER_BRANCH`.
  - AccessLint CI stores accessibility logs in Circle CI artifacts
    for every build. It compares logs for new builds against the last
    successful build on the mainline branch (default `master`). This
    setting specifies `staging` as the branch with which to compare new
    results.
- Run a detached jekyll server for crawling and analysis.
- Scan the host served via jekyll with `accesslint-ci`
### Example scenario
- Developer branches from the development branch (`staging`).
- Developer makes changes that introduce accessibility issues (form element with a missing label).
- Developer opens a pull request in GitHub with the changes.
- Developer gets a comment notification that his or her PR introduced 1 new error, including the url, criticality, and CSS selector of the failing element, like so:

```
'http://localhost:4000/form-templates/ | serious | Form elements must have labels | ["#\\30 3-sign-in-form > .preview > .usa-form > fieldset > input:nth-of-type(2)", "#\\30 4-password-reset-form > .preview > .usa-form > fieldset > .js-validate_password"]'
```
### Circle CI setup

To get comments working:
- Set the following in [Circle CI environment variables](https://circleci.com/gh/18F/web-design-standards/edit#env-vars)
  - `ACCESSLINT_GITHUB_TOKEN` - [GitHub personal access token](https://github.com/settings/tokens/new)
    from a [collaborator account with write permissions](https://github.com/18F/web-design-standards/settings/collaboration)
  - `CIRCLE_TOKEN` - [Circle CI API token](https://circleci.com/account/api)

### CODE REVIEW

**Comment by ckundo** [comment]
As soon as you set the `ACCESSLINT_GITHUB_TOKEN` and `CIRCLE_TOKEN` in your CircleCI environment (see the PR description), accesslint-ci will post comments.

See https://circleci.com/gh/accesslint/web-design-standards-docs/4 for the output that will be posted.

```
'http://localhost:4000/about-our-work/product-roadmap/ | critical | ARIA attributes must conform to valid values | ["#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(1) > .usa-label.label-done", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(2) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(3) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(4) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(5) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(7) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(8) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(9) > .usa-label.label-in-progress"]'
'http://localhost:4000/about-our-work/product-roadmap/ | critical | id attribute value must be unique | ["#main-content > .styleguide-content.usa-content > section:nth-of-type(1)"]'
'http://localhost:4000/assets/files/uswds-assets-ai.zip | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:4000/assets/files/uswds-assets-eps.zip | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:4000/assets/files/uswds-assets-omnigraffle.zip | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:4000/assets/files/uswds-assets-sketch.zip | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:4000/form-controls/ | critical | id attribute value must be unique | ["#\\30 1-text-input > .usa-accordion-bordered.usa-accordion-docs > .usa-accordion-content"]'
'http://localhost:4000/form-templates/ | critical | id attribute value must be unique | ["#\\30 1-name-form > .usa-accordion-bordered.usa-accordion-docs > .usa-accordion-content", "#\\30 3-sign-in-form > .preview > .usa-form > fieldset > input:nth-of-type(2)"]'
'http://localhost:4000/form-templates/ | serious | Form elements must have labels | ["#\\30 3-sign-in-form > .preview > .usa-form > fieldset > input:nth-of-type(2)", "#\\30 4-password-reset-form > .preview > .usa-form > fieldset > .js-validate_password"]'
'http://localhost:4000/getting-started/developers/CONTRIBUTING.md | serious | <html> element must have a valid lang attribute | ["html"]'
'http://localhost:4000/typography/ | critical | id attribute value must be unique | ["#\\30 3-typesetting > .usa-accordion-bordered.usa-accordion-docs > .usa-accordion-content"]'```

cc @maya @nickbristow

**Comment by yozlet** [comment]
Fantastic, thank you!

Question about the `ACCESSLINT_GITHUB_TOKEN`: What permissions does this token need? Is it just adding comments to PRs, or other things as well?

**Comment by ckundo** [comment]
@yozlet the token only needs commenting permissions. The request it makes happens here: https://github.com/accesslint/accesslint-ci/blob/master/lib/accesslint/ci/commenter.rb#L15

We're working on oauth, but I can securely send you a token and you can add @accesslint-ci as a collaborator to the project.

**Comment by ckundo** [comment]
We just set up a support channel at http://accesslint-slack.herokuapp.com in case there's any questions we can answer @maya @yozlet @fureigh

**Comment by ckundo** [comment]
@shawnbot we’re working on a way to comment that uses github integrations, sans full access token. Keep an eye on the project here github.com/accesslint/accesslint-ci, and I'll also followup here.

**Comment by ckundo** [comment]
Hi @shawnbot and crew! In order for @accesslint-ci to comment on **private** repos, it'd need collaborator status with write access. This is how @houndci-bot works for private repos. However, since this repo is public, there's no write access needed! We're standing up a standalone service to post comments on public repos. I'll update the PR once that's in place.

**Comment by ckundo** [comment]
Hi @shawnbot! You no longer need to add accesslint-bot as a collaborator. See https://github.com/18F/18f.gsa.gov/pull/2134 for an example implementation (you can probably mostly copy that PR).

**Pull request closed without merging**
