### PR TITLE
CC 18F bizdev to inquiry email link

### PR DESCRIPTION
**Pull request by maya**
- Adds `+training` and `+customization` to email links for ease of filtering. See: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html
- Adds cc to 18F business development

cc @d-kenny

### CODE REVIEW

**Comment by maya** [comment]
Since we're adding the cc inquiries18F@gsa.gov, we can always search by that and probably don't need the `+training` so removed in 8d938ba.

**Comment by thisisdano** [comment]
It was such a clever solution, I kinda miss it.

**Comment by maya** [comment]
@thisisdano We can re-add it, do you like the idea of just having it say `+inquiry` for both or have it grouped out?

**Comment by thisisdano** [comment]
I like it grouped out as `+training` and `+customization`

**Comment by maya** [comment]
Np! Quick question: on the latest home page designs we found, "customization" changed to "consultation"... is that something we plan on doing. @donjo do you recall if 18F bizdev wanted that phrasing? 

cc @d-kenny @MKathrynC

**Comment by donjo** [comment]
@maya I can't remember whether or not that was a suggestion or an ad-hoc decision. I do remember it being discussed whether or not "training" would be something that we mention/offer on the homepage but not sure where the team stands on that today so better to let the folks you cc'd chime in.

**Comment by maya** [comment]
It sounds like we're removing "Training." @thisisdano @donjo any preference on the display below:

screen shot 2017-11-08 at 8 51 31 am
screen shot 2017-11-08 at 9 50 14 am
screen shot 2017-11-08 at 8 58 39 am

**Comment by maya** [comment]
Re-added +training and +customization to email links in 13d16ae. 

Holding off on content changes until @d-kenny has a meeting to decide this next Weds. 

This is ready to review.

**Comment by donjo** [comment]
@maya FWIW I like the third option of the new content styles when it comes to tackling that in a new issue. I'll review this so the address changes can get pulled in now

**Pull request merged**
