### PR TITLE
Close span in the landing hero callout

### PR DESCRIPTION
**Pull request by nschonni**
## Description

Minor validation issue found running https://validator.w3.org/nu/?doc=https%3A%2F%2Fstandards.usa.gov%2F

### CODE REVIEW

**Comment by maya** [comment]
@nschonni thanks so much for finding this. We're hoping this may get resolved in #450, which uses the code from https://github.com/18F/web-design-standards. /cc @donjo

**Comment by nschonni** [comment]
I think I follow. You're saying eventually this https://github.com/18F/web-design-standards/blob/de246aef2df86ebd8f0f15ebe0eef9f0e5d5fe61/src/components/layouts/landing.njk will get pull/generated and this file will get deleted.
Feel free to close

**Comment by maya** [comment]
It appears to be closing properly here so I think we're good: https://github.com/18F/web-design-standards/blob/develop/src/components/hero/hero.njk#L6 Feel free to let us know if you find anything else, we appreciate it!

**Comment by maya** [comment]
I realized I misunderstood this PR and you were correct. Looks good to me.

**Comment by nschonni** [comment]
Thanks, you're 💯  right that the upstream patch will make it obsolete once the site is re-templated. This is just a temporary band-aid

**Pull request merged**
