### PR TITLE
Add links to 4 callouts on homepage

### LINKED ISSUE #391: Update links on featured content on homepage
screen shot 2017-08-30 at 3 22 22 pm

the 4 featured sections on the homepage should link to their respective sections of the site.

### PR DESCRIPTION
**Pull request by maya**
Fixes #391

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/add-home-links)

Wanted to check we liked the text of the links... "See getting started," "See UI components," etc...

### CODE REVIEW

**Comment by donjo** [comment]
screen shot 2017-11-06 at 1 37 13 pm

currently seeing a bug where part of the focus state is cut off because the following:

```
.usa-media_block-body {
    overflow: hidden;
}
```

Is this still needed or is it a relic of a previous media_block style?

**Comment by maya** [comment]
The media block style wasn't previously in use, but I made it in use on medium and small sizes (if you resize it smaller). Up to us if we want to keep it or not.

**Comment by thisisdano** [comment]
Let's try some link text that's a bit more engaging.

screen shot 2017-11-06 at 1 25 13 pm

`Take the first step`
`Browse the components`
`See what's new`
`Start from a template`

Something like that?

**Comment by maya** [comment]
@thisisdano text updated in 19ddfed.

**Comment by donjo** [comment]
Forgot to add a comment saying let's take the discussion to styling these (and whether they should use that overflow piece) to a new issue.

**Pull request merged**
