### PR TITLE
[About our work]: Add Research page

### PR DESCRIPTION
**Pull request by maya**
## Description

Adds Research page to About our work.

### *Ignore second nav/sidebar - it's a glitch with the sitcky nav + screenshot software
hkuzoglqdiaaaaasuvork5cyii

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

/cc @kategarklavs @jameshupp

### CODE REVIEW

**Comment by kategarklavs** [comment]
@maya Thank you for creating this — it looks great(!)

**Comment by kategarklavs** [comment]
@donjo Ahhh, good call — thanks for the suggestion. I'm all in favor of listing the findings chronologically.

**Comment by maya** [comment]
@donjo: @jameshupp updated the content in 6560b47.

**Comment by acolter** [comment]
Took a look at the updates in [6560b47](https://github.com/18F/web-design-standards-docs/commit/6560b47b6e792f33c2f99a7989c1960a4695c2e9) and have a few comments: 

- Suggest changing "Pre-1.0 field observations - June 2016" to "Field observations - June 2016" since it may not be clear to the lay user what "Pre-1.0" means or why it's relevant. It's referred to as Pre-1.0 Release in the research wiki, suggest replacing it with "Field observations - June 2016"  there as well. 
- In the "Listening tour findings - August 2016" section, since the heading mentions the date, starting the listening tour paragraph with "In August 2016" is probably unnecessary.

**Comment by juliaelman** [comment]
@acolter updated here a94de03

**Comment by acolter** [comment]
I'd recommend keeping the date in the Listening tour findings - August 2016 heading. My suggestion was to remove the reference to the date in the paragraph.

**Comment by juliaelman** [comment]
@acolter fixed here a8b54b7

**Pull request merged**
