### PR TITLE
Updating path for gulp sass linting task.

### PR DESCRIPTION
**Pull request by juliaelman**
This pull request makes the path point to the root level dir for `scss-lint` to do it's job correctly. We are discussing moving to [`stylelint`](https://github.com/stylelint/stylelint) in the future, but will be sticking with `scss-lint` for the time being.

//cc @yozlet

### CODE REVIEW

**Comment by juliaelman** [comment]
Updated path in `.scss-lint.yml` file to point to new assets architecture.

**Comment by yozlet** [comment]
Yay, good catch! :shipit:

**Comment by yozlet** [comment]
(or rather, :shipit: once the merge conflicts are resolved)

**Comment by juliaelman** [comment]
Merge conflicts resolveth 🚀

**Pull request merged**
