### PR TITLE
Publish performance pages, and make nav link visible

### PR DESCRIPTION
**Pull request by shawnbot**
### [:eyes: Preview on Federalist](https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/develop/performance/)

Reviewers: Please take a look at everything here, click around on some of the links, and let us know if anything doesn't work or needs some more editing. Thank you!!

### CODE REVIEW

**Comment by donjo** [comment]
Running list of things I see

- [ ]  The top level of the Performance Guide header doesn't have the "Getting Started" subhead/label/tag that the other sections do. 
screen shot 2017-05-11 at 4 40 41 pm

- [ ]  The intro sentence on "Why track performance" is unfinished"
    > Performance is an important part of user experience that shouldn’t go unnoticed [need better intro].

- [ ]  Lists longer than content width. I think this is already an issue somewhere but I'd like to see if we can get a fix for that in before publishing
screen shot 2017-05-11 at 4 44 32 pm

- [ ]  Cleanup needed on "How" page. I'd like to fix those example boxes before we start sending traffic to this. https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/develop/performance/how/

- [ ]  Weird indent on HTTP/2 Perf guide page 
screen shot 2017-05-11 at 4 51 02 pm

**Comment by donjo** [comment]
FYI I'm taking on all the formatting things currently so just need help on the content pieces.

**Comment by msecret** [comment]
Another thing: the research isn't there yet. I have another PR for it: https://github.com/18F/web-design-standards-docs/pull/292.

Can we merge that first?

**Comment by msecret** [comment]
@donjo I don't understand what you mean by: "The top level of the Performance Guide header doesn't have the "Getting Started" subhead/label/tag that the other sections do"

**Comment by msecret** [comment]
I created a PR to address they why section not having a complete lead: https://github.com/18F/web-design-standards-docs/pull/295

**Comment by msecret** [comment]
@donjo I created a new issue for the example sections: https://github.com/18F/web-design-standards/issues/1924. Please add anything else to that issue that needs to be done

**Comment by msecret** [comment]
I think we have to pull in some new changes to this. I'll take a look at doing that.

**Comment by msecret** [comment]
Nvm, I just realized, those things will be available on the develop branch when they get merged.

**Comment by donjo** [comment]
ok I just put in a PR #301 that addresses all but one thing in my checklist (some of the other things rely on 1.2 but that's fine to happen whenever it happens). 

However, I can't figure out the first item in the list. The category on `overview.md` is set to `Getting started` like it should be but it doesn't seem to get the site subheading properly. Any ideas?

**Comment by donjo** [comment]
I think this is good to go. Will create a separate issue for that last thing about the "Getting Started" subhead label and formatting things will get cleaned up with 1.2's release.

**Pull request merged**
